
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables or hardcoded values for the Supabase connection
const SUPABASE_URL = "https://iegyfxoycykisscfktxq.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllZ3lmeG95Y3lraXNzY2ZrdHhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyOTE5MzMsImV4cCI6MjA1NTg2NzkzM30.MJj0aVJ8Q72rsXudyI0NEDfoxA7LckvXqifbS4_xtrM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);

// Add connection status check function for debugging
export const checkSupabaseConnection = async () => {
  try {
    const { data, error } = await supabase.from('listings').select('id').limit(1);
    if (error) {
      console.error('Supabase connection check error:', error);
      return false;
    }
    console.log('Supabase connection successful');
    return true;
  } catch (err) {
    console.error('Supabase connection failed:', err);
    return false;
  }
};
